openapi: "3.0.0"
info:
  version: "1.0.0"
  title: Account Service API
  description: The account-service API is part of the FTGOGO demonstration application
  contact:
    name: FTGOGO Issues
    url: https://github.com/stackus/ftgogo/issues
servers:
  - url: https://{host}:{port}/api
    variables:
      host:
        default: localhost
      port:
        default: "8001"
paths:
  /accounts/{accountID}:
    get:
      summary: Get basic information for an account by ID
      operationId: getAccount
      parameters:
        - $ref: '#/components/parameters/AccountID'
      responses:
        '200':
          $ref: '#/components/responses/AccountIDResponse'
        default:
          $ref: '../../../shared-go/web/spec.yaml#/components/responses/ErrorResponse'
  /accounts/{accountID}/disable:
    put:
      summary: Disable an account by ID
      operationId: disableAccount
      parameters:
        - $ref: '#/components/parameters/AccountID'
      responses:
        '200':
          $ref: '#/components/responses/AccountIDResponse'
        default:
          $ref: '../../../shared-go/web/spec.yaml#/components/responses/ErrorResponse'
  /accounts/{accountID}/enable:
    put:
      summary: Enable an account by ID
      operationId: enableAccount
      parameters:
        - $ref: '#/components/parameters/AccountID'
      responses:
        '200':
          $ref: '#/components/responses/AccountIDResponse'
        default:
          $ref: '../../../shared-go/web/spec.yaml#/components/responses/ErrorResponse'

components:
  schemas:
    MenuItemQuantities:
      type: object
      additionalProperties:
        type: integer
  parameters:
    AccountID:
      in: path
      name: accountID
      description: account id (uuid)
      required: true
      schema:
        type: string
        format: uuid
  responses:
    AccountIDResponse:
      description: OK
      content:
        application/json:
          schema:
            type: object
            required: [ id ]
            properties:
              id:
                type: string
